version: '3'
services:
  database:
    image: nayzow/endpoint-sh-database
    ports:
      - "3306:3306"

  api:
    image: nayzow/endpoint-sh-backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  app:
    image: nayzow/endpoint-sh-frontend
    ports:
      - "80:80"